### ISSUE TITLE
API-Test : Create a Frontend UI with React 🚀 

### ISSUE THREAD

**Issue by yezz123** [yezz123/FRDP#3]
The API should communicate without errors with a simple React UI:

the basic usage is usable: 

- Authenticate the new user
- Register a new user
- Edit User
- Logout (Working on it)

**Comment by Elamurugan-Nallathambi** [comment]
Hello @yezz123  

Do you have preference on what kind of frontend packages needs to be used to build this? I guess I will try to build a react frontend with Tailwind to contribute if thats ok with you.

**Comment by yezz123** [comment]
> Hello @yezz123
> 
> Do you have preference on what kind of frontend packages needs to be used to build this? I guess I will try to build a react frontend with Tailwind to contribute if thats ok with you.

Literally is amazing I'm thinking to of reactJs and Tailwind this last Version look amazing, I appreciate  @Elamurugan-Nallathambi 🙏🏻
